version: '3.4'

services:

  epiccollections.db:
    container_name: epiccollectionsdb
    hostname: epiccollectionsdb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: N3ts1mpl3bl0g@

networks:
  default: 
    name: service_epiccollections

